### ISSUE TITLE
Azure:failed to start scylla-machine-image service during image build

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla-machine-image#190]
During azure build we keep getting failures every few builds with the following error:
```
05:18:20  [0;32m    azure-arm: The following packages have unmet dependencies:[0m
05:18:20  [0;32m    azure-arm:  scylla-machine-image : Depends: scylla but it is not going to be installed[0m
05:18:20  [1;31m==> azure-arm: E: Unable to correct problems, you have held broken packages.[0m
05:18:20  [1;31m==> azure-arm: Traceback (most recent call last):[0m
05:18:20  [1;31m==> azure-arm:   File "/home/azureuser/scylla_install_azure", line 83, in <module>[0m
05:18:20  [1;31m==> azure-arm:     run('apt-get install -y --auto-remove --allow-unauthenticated {0}-machine-image {0}-server-dbg systemd-coredump'.format(args.product))[0m
05:18:20  [1;31m==> azure-arm:   File "/home/azureuser/scylla_install_azure", line 39, in run[0m
05:18:20  [1;31m==> azure-arm:     return subprocess.check_call(cmd, shell=shell, env=my_env)[0m
05:18:20  [1;31m==> azure-arm:   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call[0m
05:18:20  [1;31m==> azure-arm:     raise CalledProcessError(retcode, cmd)[0m
05:18:20  [1;31m==> azure-arm: subprocess.CalledProcessError: Command '['apt-get', 'install', '-y', '--auto-remove', '--allow-unauthenticated', 'scylla-machine-image', 'scylla-server-dbg', 'systemd-coredump']' returned non-zero exit status 100.[0m
05:18:20  [1;31m==> azure-arm: Script exited with non-zero exit status: 1.Allowed exit codes are: [0][0m
05:18:20  [1;31m==> azure-arm: Step "StepProvision" failed, aborting...[0m
05:18:20  [1;31m==> azure-arm: aborted: skipping cleanup of step "StepConnectSSH"[0m
05:18:20  [1;31m==> azure-arm: aborted: skipping cleanup of step "StepGetIPAddress"[0m
05:18:20  [1;31m==> azure-arm: aborted: skipping cleanup of step "StepDeployTemplate"[0m
05:18:20  [1;31m==> azure-arm: aborted: skipping cleanup of step "StepValidateTemplate"[0m
05:18:20  [1;31m==> azure-arm: aborted: skipping cleanup of step "StepCreateResourceGroup"[0m
05:18:20  [1;31mBuild 'azure-arm' errored after 2 minutes 41 seconds: Script exited with non-zero exit status: 1.Allowed exit codes are: [0][0m
```
Happend in https://jenkins.scylladb.com/view/master/job/scylla-master/job/azure-image/32/consoleFull and also https://jenkins.scylladb.com/view/master/job/scylla-master/job/azure-image/24/console

@syuu1228 when we saw this same error in https://github.com/scylladb/scylla-machine-image/pull/132 you mention one possible fix , can you please have a look ?

**Comment by syuu1228** [comment]
@yaronkaikov It unlikely related with #132, more like debian package build problem, but I haven't able get detail of the problem for now because I couldn't reproduce it.

I sometimes see this error when I work on packaging, it occurs usually when jmx/tools/python3 packages are not exactly same version compare to scylla metapackage.
It can happen on following steps:
 1. build everything including jmx/tools/python3 packages
 2. repository updated to new version
 3. build scylla-server packages only
But I guess it should not occur on Jenkins, so I'm not sure how it's happens.

I'm trying to reproduce the error `The following packages have unmet dependencies: scylla-machine-image : Depends: scylla but it is not going to be installed` on exactly same repository on Azure Ubuntu image, and also local vagrant Ubuntu image, but never succeeded to reproduce it for now. It even succeed on Jenkins, with same repository (downloads.scylladb.com/unstable/scylla/master/deb/unified/2021-08-24T00:59:30Z/scylladb-master/scylla.list).

**Comment by yaronkaikov** [comment]
Issue is no longer happened , closing, in case it will appear again we will re-open
